name: Build geoip.dat
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "**/dependabot.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v3.2.0

      - name: Get IPList for China by IPIP.NET
        run: |
          curl -L "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt" -o china_ip_list.txt

      - name: Build geoip.dat
        run: |
          go run ./ --chinaip=./china_ip_list.txt

      - name: Generate geoip.dat sha256 checksum
        run: sha256sum geoip.dat > geoip.dat.sha256sum

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          mv geoip.dat geoip.dat.sha256sum ./publish

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add geoip.dat geoip.dat.sha256sum
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f geoip release

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload geoip.dat
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/geoip.dat
          asset_name: geoip.dat
          asset_content_type: application/octet-stream

      - name: Upload geoip.dat.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/geoip.dat.sha256sum
          asset_name: geoip.dat.sha256sum
          asset_content_type: text/plain
